services:
  shome-front:
    image: node:20
    container_name: shome-front
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
      - 5173:5173
    volumes:
      - .:/app
      - /app/node_modules
